name: Build Tauri App for Windows 7

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-windows7:
    strategy:
      matrix:
        platform: [windows-2019]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js (Windows 7 compatible)
        uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: "npm"

      - name: Setup Rust (Windows 7 compatible)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Setup MSVC (Windows 7 compatible)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          vsversion: "2019"

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Install Node dependencies
        run: npm ci

      - name: Build Tauri app for Windows 7
        run: npm run tauri build
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

      - name: Upload Windows 7 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-app-windows7
          path: |
            src-tauri/target/release/bundle/
            !src-tauri/target/release/bundle/**/.*
